export type { User } from './user'
export type { Album } from './album'
export type { Post } from './post'
export type { Comment } from './comment'
export type { Photo } from './photo'

export { userSchema } from './user'
export { albumSchema } from './album'
export { postSchema } from './post'
export { commentSchema } from './comment'
export { photoSchema } from './photo'
