name: Cypress CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["main"]

jobs:
  cypress-tests:
    runs-on: self-hosted
    container:
      image: cypress/included:9.5.1-node16.14.0-slim-chrome99-ff97
    env:
      CYPRESS_CACHE_FOLDER: /root/.cache/Cypress

    steps:
      - name: Set permissions
        run: chmod -R a+rwX /root/.cache

      - uses: actions/checkout@v2

      - name: Cypress component tests
        uses: cypress-io/github-action@v2
        with:
          command: npx cypress run-ct --config video=false,screenshotOnRunFailure=false

      - name: Build nextjs
        run: npm run build
